=== kzubrinic/ris/dis_examples/data/studenti.dtd
<!ELEMENT Studenti (Osoba, Studij?, Adresa?, KontaktPodaci?)>
 	<!ELEMENT Osoba (Ime, Prezime?)>
 		<!ELEMENT Ime (#PCDATA)>
 		<!ELEMENT Prezime (#PCDATA)>
 	<!ELEMENT Studij (#PCDATA)>
 	<!ELEMENT Adresa (Ulica?, Broj?, Grad?)>
 		<!ELEMENT Ulica (#PCDATA)>
 		<!ELEMENT Broj (#PCDATA)>
 		<!ELEMENT Grad (#PCDATA)>
 	<!ELEMENT KontaktPodaci (Telefon*, Email+, KorisnickoIme+)>
 		<!ELEMENT KorisnickoIme (#PCDATA)>
 		<!ELEMENT Telefon (#PCDATA)>
 		<!ELEMENT Email (#PCDATA)>
  <!ATTLIST Telefon vrsta (Fiksni|Mobilni) #IMPLIED>
  <!ATTLIST Osoba id ID #REQUIRED>

=== kzubrinic/ris/dis_examples/data/studenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Studenti SYSTEM "studenti.dtd" >
<Studenti>
  <Osoba id="o-12345">
 		<Ime>Pero</Ime>
 		<Prezime>Perić</Prezime>
 	</Osoba>
 	<Studij>Sistem analitičar</Studij>
 	<Adresa>
 		<Ulica>U gradu</Ulica>
 		<Broj>247</Broj>
 		<Grad>Zagreb</Grad>
 	</Adresa>
 	<KontaktPodaci>
 		<Telefon>01-111-777</Telefon>
 		<Telefon vrsta="Mobilni">098-111-1778</Telefon>
 		<Email>pperic@zg.tel.hr</Email>
 		<KorisnickoIme>pperic</KorisnickoIme>
 	</KontaktPodaci>
 </Studenti>
